project:
  type: website

website:
  title: "Having Fun With LLMs: Experimenting with AI"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css

execute:
  freeze: auto


